<a href="https://colab.research.google.com/github/Slyther12/Python/blob/main/NumPy/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

- NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

- At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [2]:
#For importing numpy
!pip install numpy
import numpy as np

In [3]:
#For creating 1D array (vector)
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
#For creating 2D array (matrix)
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
#For creating 3D array (Tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


- We can create array of as much as dimension we want, there is no restriction for it.

In [6]:
#Using dtype for creating array of desirable data type
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [7]:
np.array([1,2,3], dtype=int)

array([1, 2, 3])

In [9]:
np.array([0,1,2,3], dtype=bool)

array([False,  True,  True,  True])

In [10]:
#Using np.arange to create numpy array. It works similar to range in python
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#Using strides to skip
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
#np.arange with reshape.
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
#np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
#np.random
np.random.random((3,4))

array([[0.22214909, 0.31165025, 0.62085138, 0.52636004],
       [0.62205451, 0.14536363, 0.74072306, 0.89273142],
       [0.24530323, 0.21781322, 0.22665972, 0.15672588]])

In [21]:
#np.linspace :- create array of linearly separable points
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [25]:
#np.identity :- Use to create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

NumPy Array Attributes

In [34]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [31]:
#ndim :- give No of dimension of an array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [32]:
#shape :- give no of row & column in an array
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [35]:
#size :- give the no. of element in an array
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [36]:
#itemsize :- give the size taken by each element in memory
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


Changing Datatype of NumPy Array

In [37]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

NumPy Array Operation

In [40]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


- Scalar Operations

In [43]:
#Arithmetic (+,-,/,*,%,//,**)
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [50]:
#Relational (>,<,>=,<=,==,!=,<>)
a2 != 15

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

- Vector Operations

In [51]:
#Arithmetic (+,-,/,*,%,//,**)
#Note :- Shape of array must be same
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Numpy Array Functions

In [52]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[89., 53., 12.],
       [99., 94., 84.],
       [52., 25., 13.]])

In [58]:
#max, min, sum, prod
np.max(a1, axis=0) #col = 0, row = 1

array([99., 94., 84.])

In [54]:
np.min(a1)

np.float64(12.0)

In [55]:
np.sum(a1)

np.float64(521.0)

In [56]:
np.prod(a1)

np.float64(747783987350400.0)

In [59]:
#mean, median, std, var
np.mean(a1)

np.float64(57.888888888888886)

In [62]:
np.median(a1)

np.float64(53.0)

In [61]:
np.std(a1)

np.float64(33.1744360898048)

In [60]:
np.var(a1)

np.float64(1100.5432098765432)

In [63]:
#trignometric functions sin, cos, tan
np.sin(a1)

array([[ 0.86006941,  0.39592515, -0.53657292],
       [-0.99920683, -0.24525199,  0.73319032],
       [ 0.98662759, -0.13235175,  0.42016704]])

In [64]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [65]:
#log and exponents
np.log(a1)

array([[4.48863637, 3.97029191, 2.48490665],
       [4.59511985, 4.54329478, 4.4308168 ],
       [3.95124372, 3.21887582, 2.56494936]])

In [66]:
np.exp(a1)

array([[4.48961282e+38, 1.04137594e+23, 1.62754791e+05],
       [9.88903032e+42, 6.66317622e+40, 3.02507732e+36],
       [3.83100800e+22, 7.20048993e+10, 4.42413392e+05]])

In [ ]:
#round, floor, ceil

In [80]:
a4 = np.random.random((2,3))*100
a4

array([[36.93219473, 82.47675672, 79.74410197],
       [53.07188969, 13.31545947, 67.17570753]])

In [81]:
np.round(a4)

array([[37., 82., 80.],
       [53., 13., 67.]])

In [82]:
np.floor(a4)

array([[36., 82., 79.],
       [53., 13., 67.]])

In [83]:
np.ceil(a4)

array([[37., 83., 80.],
       [54., 14., 68.]])

Indexing

In [84]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [85]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
a1[-1]

np.int64(9)

In [87]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
a2[1,0]

np.int64(4)

In [91]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [92]:
a3[1,0,1]

np.int64(5)

In [93]:
a3[0,0,0]

np.int64(0)

In [94]:
a3[1,1,0]

np.int64(6)

Slicing

In [95]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a1[2:5]

array([2, 3, 4])

In [98]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
a2[0,:]

array([0, 1, 2, 3])

In [103]:
a2[:,2]

array([ 2,  6, 10])

In [105]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [106]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [107]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [112]:
a2[1,::3]

array([4, 7])

In [113]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [116]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [129]:
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [124]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [123]:
a3[1,:,1]

array([10, 13, 16])

In [120]:
a3[0,1]

array([3, 4, 5])

In [117]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [118]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Iterating NumPy Array

In [136]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [135]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [132]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [137]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [138]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [ ]:
#reshape

In [141]:
#transpose
print(a2)
print(np.transpose(a2))
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [142]:
#ravel :- convert all dimension to 1D
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Stacking

In [143]:
#Horizontal Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [145]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
#Vertical Stacking

In [146]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [147]:
#Horizontal Splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [153]:
#Vertical Splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [154]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]